src/routes/+layout.svelte
Reduserte margins på venstre og høyre side med litt. Enda mer på mobil, fordi der er det mer begrenset med plass.
=> make page wider on desktop and mobile

src/routes/display/+layout.svelte, src/routes/display/+page.svelte
Yes, I know that the code is ugly, but if anyone that is more skilled at this than me is interested in the changes and want to fix it, go ahead.
=> Made QR code bigger and all the way down and to the left

src/routes/admin/frontdesk/+page.svelte, src/routes/admin/frontdesk/Cart.svelte, src/routes/admin/frontdesk/ItemSelection.svelte, src/routes/admin/frontdesk/OrderList.svelte
La til en kommentar for endringer som bør gjøres etter #51
=> separate frontdesk into components

src/routes/admin/frontdesk/Cart.svelte
=> show item count in cart

src/routes/admin/+layout.svelte
=> Make admin back button go correct

.github/workflows/pocketbase-typegen.yml
Fikse conditionen, passe output riktig
=> Typegen action men fikset for fjerde gang

.github/workflows/pocketbase-typegen.yml
=> types: fix if condition on pr job

.github/workflows/pocketbase-typegen.yml
Koden blir mer rotete, men den virker i hvertfall (forhåpentligvis)
=> types: workflow in single job

.github/workflows/pocketbase-typegen.yml
=> types: fix typo in workflow

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml, .github/PULL_REQUEST_TEMPLATE.md
Har foreløpig bare bug, feature og annet (tom issue), men tenker det er nok.
=> github: issue and pr templates

.github/ISSUE_TEMPLATE/bug.yaml, .github/ISSUE_TEMPLATE/feature.yaml
Testet i en private repo at det virker denne gangen :)
=> github: fix issue templates

makefile
shows more relevant info first
=> lint: format last

src/lib/stores/orderStore.ts, src/routes/admin/+page.svelte
=> admin: reset orders button

scripts/sync-db.js, src/lib/stores/authStore.ts, src/lib/types.ts
=> treewide: fix minor issues

src/routes/admin/+page.svelte, src/routes/admin/stats/+page.svelte
Makes it so it is unaffected by status
=> stats: move out of orders

src/lib/components/RefreshButton.svelte, src/lib/stores/pbStore.ts, src/lib/stores/statusStore.ts, src/routes/+layout.svelte, src/routes/admin/+layout.svelte
=> Fix reset button

src/routes/admin/menu/+page.svelte, src/routes/admin/menu/customization/+page.svelte
I messed up in #173 and forgot to make the href strings into backticks such that it actually works as intended.
=> menu: fix broken edit href's

flake.nix, src/routes/admin/orders/frontdesk/CustomizationSelection.svelte
=> admin/frontdesk: fix scrolling

pocketbase/Dockerfile
=> docker: temp comment pb migrations

docker-compose.coolify.yml
=> Coolify compose

src/routes/display/+layout.svelte
=> display: fix message when open
